// techs api

import { NextResponse } from 'next/server';

export async function GET() {
  const technologies = [
    {
      id: 1,
      name: 'Web Applications',
      category: 'Frontend',
      icon: 'Globe',
      description: 'Modern, responsive websites that work perfectly on all devices and provide exceptional user experience.',
      gradient: 'from-blue-400 to-cyan-400',
      level: 95,
      projects: 120,
      businessValue: 'Increase customer engagement by 300%',
    },
    {
      id: 2,
      name: 'E-commerce Solutions',
      category: 'Business',
      icon: 'ShoppingCart',
      description: 'Complete online stores with secure payment processing and inventory management that boost sales.',
      gradient: 'from-green-400 to-emerald-500',
      level: 92,
      projects: 85,
      businessValue: 'Average 40% increase in online sales',
    },
    {
      id: 3,
      name: 'Mobile Apps',
      category: 'Mobile',
      icon: 'Smartphone',
      description: 'Native-quality mobile applications that reach your customers wherever they are.',
      gradient: 'from-purple-400 to-pink-500',
      level: 88,
      projects: 95,
      businessValue: 'Reach 80% more customers',
    },
    {
      id: 4,
      name: 'Database Systems',
      category: 'Backend',
      icon: 'Database',
      description: 'Secure, fast data storage solutions that keep your business information safe and accessible.',
      gradient: 'from-blue-600 to-indigo-700',
      level: 90,
      projects: 110,
      businessValue: '99.9% data security guarantee',
    },
    {
      id: 5,
      name: 'AI Solutions',
      category: 'Innovation',
      icon: 'Bot',
      description: 'Smart automation tools that save time and reduce operational costs for your business.',
      gradient: 'from-yellow-400 to-orange-500',
      level: 85,
      projects: 75,
      businessValue: 'Save 50% operational costs',
    },
    {
      id: 6,
      name: 'Cloud Hosting',
      category: 'Infrastructure',
      icon: 'Cloud',
      description: 'Reliable, scalable hosting solutions that ensure your website is always online and fast.',
      gradient: 'from-cyan-400 to-blue-500',
      level: 82,
      projects: 65,
      businessValue: '99.9% uptime guarantee',
    },
    {
      id: 7,
      name: 'Security Solutions',
      category: 'Security',
      icon: 'Shield',
      description: 'Advanced security measures that protect your business and customer data from threats.',
      gradient: 'from-red-400 to-pink-500',
      level: 87,
      projects: 80,
      businessValue: 'Zero security breaches',
    },
    {
      id: 8,
      name: 'Analytics & Reports',
      category: 'Analytics',
      icon: 'BarChart3',
      description: 'Detailed insights and reports that help you make data-driven business decisions.',
      gradient: 'from-green-500 to-teal-500',
      level: 78,
      projects: 45,
      businessValue: 'Improve decision making by 60%',
    },
    {
      id: 9,
      name: 'API Integration',
      category: 'Integration',
      icon: 'Link',
      description: 'Seamless connections between your existing systems and new applications.',
      gradient: 'from-indigo-400 to-purple-500',
      level: 83,
      projects: 70,
      businessValue: 'Streamline workflows by 70%',
    },
    {
      id: 10,
      name: 'Performance Optimization',
      category: 'Optimization',
      icon: 'Zap',
      description: 'Lightning-fast loading times that improve user experience and search rankings.',
      gradient: 'from-yellow-400 to-red-500',
      level: 75,
      projects: 35,
      businessValue: '3x faster loading times',
    },
    {
      id: 11,
      name: 'Maintenance & Support',
      category: 'Support',
      icon: 'Wrench',
      description: '24/7 technical support and regular updates to keep your systems running smoothly.',
      gradient: 'from-blue-400 to-purple-500',
      level: 80,
      projects: 40,
      businessValue: '24/7 peace of mind',
    },
    {
      id: 12,
      name: 'User Experience Design',
      category: 'Design',
      icon: 'Palette',
      description: 'Beautiful, intuitive designs that make your customers love using your products.',
      gradient: 'from-pink-400 to-purple-600',
      level: 93,
      projects: 130,
      businessValue: 'Increase user satisfaction by 85%',
    },
  ];

  return NextResponse.json(technologies);
}
