import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/master/Header";
import Footer from "@/components/master/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={`${poppins.variable}`}>
      <head>
        <link rel='preconnect' href='https://codeversoft.com' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='anonymous' />
      </head>
      <body className={`flex min-h-screen flex-col bg-gradient-to-r from-[#152E55] to-[#000000] antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
